import type { Metadata } from "next";
import { lora, poppins } from "./fonts";
import "./globals.css";
import { Header } from "@/components/shared/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${lora.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
